env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - next/core-web-vitals
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./client/tsconfig.json
    - ./tsconfig.eslint.json
plugins:
  - react
rules:
  {
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/strict-boolean-expressions": 0,
    "@typescript-eslint/restrict-template-expressions": 0,
    "eqeqeq": 0,
    "@typescript-eslint/no-misused-promises": 0,
  }
