# docker next js prod

FROM node:16-alpine

WORKDIR /app

COPY package.json .

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm add sharp

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]