version: '3.2'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app