version: "3.2"
services:
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - /app/node_modules
      - ./client:/app
      - /app/.next
  server:
    build: ./server
    expose:
      - 4000
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - ./server:/app
    restart: always
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - my-network
    environment:
      - REDIS_PASSWORD=password123
    volumes:
      - ./redis:/data
volumes:
  data:
networks:
  my-network:
