version: '3.2'
services:
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ./server
    expose:
      - 4000
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - ./server:/app
volumes:
  data:
networks:
  my-network:
    